version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Mount source code for hot reloading
      - ./:/app
      # Don't override node_modules in container
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true # Improves hot reloading in some environments
      - WATCHPACK_POLLING=true # For Next.js file watching
    command: pnpm dev
    networks:
      - boring-network

networks:
  boring-network:
    driver: bridge
